[package]
name = "aws_dyn_dns"
version = "0.1.0"
authors = ["Fredrik <fredrik.jonsen@zenon.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
